# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3.9"
services:
  nodejs:
    image: py-dev:${TAG}
    container_name: python_${TAG}
    volumes:
      - ${CLI_DIRECTORY}\cache\python:/data
      - ${CLI_DIRECTORY}\python\test:/app
      - ${CLI_DIRECTORY}\python\src:/app/lib
    networks:
      - request-service-arch
    working_dir: "/app"
    command: ["tail", "-f", "/dev/null"]

  json-server:
    image: json-server:${TAG}
    container_name: json-service_${TAG}
    ports:
      - 3000:3000
    networks:
      - request-service-arch
    command: ["json-server", " -H", "0.0.0.0 db.json"]

networks:
  request-service-arch:
    driver: bridge
